apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'
apply plugin: 'org.jetbrains.kotlin.plugin.parcelize'

android {
    namespace 'com.therxmv.sharedpreferences'
}

dependencies {
    implementation project(":common")

    implementation libs.core.ktx
    implementation libs.mkkv

    implementation libs.hilt.android
    kapt libs.hilt.compiler
}
