apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.dirolreader.feed.data'

    testOptions {
        unitTests {
            // android.util.Log etc. become no-ops in local unit tests
            returnDefaultValues = true
        }
    }
}

dependencies {
    implementation project(":feed:domain")
    implementation project(":channels:data")
    implementation project(":channels:domain")
    implementation project(":common")

    implementation 'com.github.tdlibx:td:1.8.56'
    implementation libs.bundles.retrofit
    implementation libs.gson

    implementation libs.core.ktx
    implementation libs.kotlinx.coroutines.core

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    testImplementation libs.bundles.testing.unit
}
