apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.dirolreader.channels.data'
}

dependencies {
    implementation project(":channels:domain")
    implementation project(":common")

    implementation libs.core.ktx

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    implementation libs.room.runtime
    kapt libs.room.compiler

    testImplementation libs.bundles.testing.unit
}
