apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.otaupdates.presentation'

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeCompiler.get()
    }

    testOptions {
        // android.util.Log stub throws "not mocked" in JVM tests otherwise
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(":common")
    implementation project(":shared-preferences")
    implementation project(":ota-updates:domain")

    implementation libs.core.ktx
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.runtime.compose
    implementation libs.accompanist.permissions

    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose.ui

    implementation libs.hilt.android
    kapt libs.hilt.compiler
    implementation libs.hilt.navigation.compose

    testImplementation libs.bundles.testing.unit
}
