apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.dirolreader.settings'

    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeCompiler.get()
    }
}

dependencies {
    implementation project(":common")
    implementation project(":shared-preferences")

    implementation libs.core.ktx
    implementation libs.kotlinx.collections.immutable

    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose.ui

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    testImplementation libs.bundles.testing.unit
}
