plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    id 'kotlin-kapt'
    alias(libs.plugins.hilt)
    id 'org.jetbrains.kotlin.plugin.parcelize'
}

android {
    namespace 'com.therxmv.dirolreader'
    compileSdk appConfig.compileSdkVersion

    defaultConfig {
        applicationId appConfig.applicationId
        minSdk appConfig.minSdkVersion
        targetSdk appConfig.targetSdkVersion
        versionCode 201
        versionName "2.0.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        Properties properties = new Properties()
        properties.load(project.rootProject.file("local.properties").newDataInputStream())

        buildConfigField "String", "API_HASH", "\"${properties.getProperty("API_HASH")}\""
        buildConfigField "Integer", "API_ID", "${properties.getProperty("API_ID")}"
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }

    splits {
        abi {
            enable true
            reset()
            include "armeabi-v7a", "arm64-v8a"
            universalApk true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion libs.versions.composeCompiler.get()
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation 'com.github.tdlibx:td:1.8.56'
    implementation project(':common')
    implementation project(':shared-preferences')
    implementation project(':ota-updates:presentation')
    implementation project(':ota-updates:domain')
    implementation project(':ota-updates:data')
    implementation project(':channels:domain')
    implementation project(':channels:data')
    implementation project(':feed:domain')
    implementation project(':feed:data')
    implementation project(':feed:presentation')
    implementation project(':settings')

    implementation libs.activity.ktx
    implementation libs.core.ktx
    implementation libs.kotlinx.collections.immutable
    implementation libs.lifecycle.runtime.ktx
    implementation libs.lifecycle.runtime.compose

    implementation libs.hilt.android
    kapt libs.hilt.compiler
    implementation libs.hilt.navigation.compose

    implementation platform(libs.compose.bom)
    implementation libs.bundles.compose.ui

    implementation libs.exoplayer
    implementation libs.toolbar.compose
    implementation libs.paging.compose
    implementation libs.compose.markdown
    implementation libs.core.splashscreen

    testImplementation libs.bundles.testing.unit
}
