apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.otaupdates.data'

    testOptions {
        // android.util.Log stub throws "not mocked" in JVM tests otherwise
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(":ota-updates:domain")
    implementation project(":common")

    implementation libs.core.ktx

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    implementation libs.bundles.retrofit
    implementation libs.gson

    testImplementation libs.bundles.testing.unit
}
