apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.otaupdates.domain'
}

dependencies {
    implementation project(":common")

    implementation libs.core.ktx

    implementation libs.hilt.android
    kapt libs.hilt.compiler
}
