apply from: "$rootDir/gradle/snippets/module-config.gradle"
apply plugin: 'kotlin-kapt'

android {
    namespace 'com.therxmv.dirolreader.feed.domain'
}

dependencies {
    implementation project(":channels:domain")
    implementation project(":common")
    implementation libs.tdlib
    implementation libs.kotlinx.coroutines.core

    implementation libs.core.ktx
    implementation libs.paging.common

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    testImplementation libs.bundles.testing.unit
}
